USE [master]
GO

/****** Object:  Database [SMS]    Script Date: 2021-03-31 오전 9:46:22 ******/
CREATE DATABASE [SMS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SMS', FILENAME = N'D:\Datas\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SMS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SMS_log', FILENAME = N'D:\Datas\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SMS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SMS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SMS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SMS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SMS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SMS] SET ARITHABORT OFF 
GO

ALTER DATABASE [SMS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SMS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SMS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SMS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SMS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SMS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SMS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SMS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SMS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SMS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SMS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SMS] SET RECOVERY FULL 
GO

ALTER DATABASE [SMS] SET  MULTI_USER 
GO

ALTER DATABASE [SMS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SMS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SMS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SMS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SMS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SMS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SMS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SMS] SET  READ_WRITE 
GO

